stages:
    - trigger
    - release
    - deploy

trigger:
    stage: trigger
    tags: [trigger]
    only: [triggers]
    script: [date]

release:
    stage: release
    tags: [trigger]
    variables: { tag: "kongrentian/tianyi:${CI_COMMIT_REF_NAME}" }
    script:
        - docker build . -t "${tag}"
        - docker push "${tag}"

deploy:
    stage: deploy
    tags: [trigger]
    script:
        - export PATH="${PATH}:/usr/libexec/docker/cli-plugins"
        - docker-compose up -d --remove-orphans
