stages:
    - trigger
    - release
    - deploy

trigger:
    stage: trigger
    tags: [trigger]
    only: [triggers]
    script: [date]

release:
    stage: release
    variables: { tag: "kongrentian/tianyi:${CI_COMMIT_REF_NAME}" }
    script:
        - docker build -t "${tag}"
        - docker push "${tag}"

deploy:
    stage: deploy
    script:
        - docker-compose up -d
