version: "3.1"

services:
    postgres:
        container_name: tianyi_postgres
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_DB: tianyi
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: "spo,h-6'383<YN%P<abr[l5Xv!o*O=+}"
        volumes:
            - ./infrastructure/app:/docker-entrypoint-initdb.d:ro
        networks:
            - tianyi
        ports:
            - "5432:5432"

    redis:
        container_name: tianyi_redis
        image: redis:7-alpine
        restart: always
        networks:
            - tianyi
        command: redis-server --requirepass "spo,h-6'383<YN%P<abr[l5Xv!o*O=+}"

    tianyi:
        container_name: tianyi_server
        image: kongrentian/tianyi:${CI_COMMIT_REF_NAME}
        volumes:
            - ./tianyi.yml:/app/tianyi.yml:ro
        networks:
            - tianyi
        depends_on:
            - postgres
            - redis

    nginx:
        container_name: tianyi_nginx
        image: nginx:1.23-alpine
        volumes:
            - ./tianyi.conf:/etc/nginx/conf.d/tianyi.conf:ro
        networks:
            - tianyi
        ports:
            - "6379:6379"
            - "443:443"

networks:
    tianyi:
