version: "3.1"

services:
    postgres:
        container_name: tianyi_postgres
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: tianyi
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - tianyi
        ports:
            - "5432:5432"

networks:
    tianyi:
